### ISSUE TITLE
(re)organizing README.rst

### ISSUE THREAD

**Issue by moideen** [EvanKepner/mutatest#13]
README.rst is quite big and requires a lot of scrolling. We can either add a table of contents and some internal links between sections, or separate out some of its content into another rst file. The latter will probably be a better choice if the future state is proper GitHub pages documentation. Thoughts?

**Comment by EvanKepner** [comment]
I'm good with a general reorg of the README to make it easier to parse, but a couple constraints:

1. There is a `tox` environment for `pypi-description` that I want to ensure remains passing because the README, AUTHORS, and CHANGELOG are all combined for the project description on PyPI: https://pypi.org/project/mutatest/

2. Given that, I'd prefer to keep a single README file (even if it's long) with a table of contents. If you look at `tqdm` it appears that RST supports this structure e.g. https://github.com/tqdm/tqdm/blob/master/README.rst

```
.. contents:: Table of contents
   :backlinks: top
   :local:
```

Which renders appropriately on PyPI: https://pypi.org/project/tqdm/

When I get around to hosting pages on readthedocs or similar the single big RST file will still split nicely, and keeping it in one big file here on GitHub means people don't have to click through files to find details.

**Comment by EvanKepner** [comment]
Lots of docs, now well organized - https://mutatest.readthedocs.io/
