### ISSUE TITLE
do not mutate assert statements

### ISSUE THREAD

**Issue by martinruefenacht** [EvanKepner/mutatest#26]
I came across this problem when mutation testing my simulator. (Congratulations to the chef, this is an awesome tool.)

I use assertions such as:
`assert nodes >= 0`

I use these assert statements to catch errors that I made quickly, sprinkled throughout the code to make sure corruptions are found early. These conditions are never supposed to be True.

Mutatest mutates the condition which makes it False even though it is a valid node count. In other words mutatest corrupts the test for a corrupt condition.

Am I thinking about this wrong or is it actually incorrect to mutate assertions?

I am also wondering how mutatest would do with parameter checking which would raise an exception. Would it also mutate the condition there and fail wrongly?

**Comment by EvanKepner** [comment]
Thanks for raising an interesting question (and for checking out `mutatest`)! This is a case I hadn't considered, the node selection process is only at the operation level - it's not context sensitive to where the operation occurs as long as the node type is matching. I've found this to be a problem with the type-hint of `None` which is a valid `NameConstant` node as another example. 

Something to try - run your tests with the `PYTHONOPTIMIZE` environment variable set - https://docs.python.org/3/using/cmdline.html#envvar-PYTHONOPTIMIZE - this optimization specifically removes `assert` statements. You'd still have the problem of `mutatest` picking it up initially in the source code scan and logging as a potential trial; however, they should always pass since the compiled pycache would (hopefully) respect the optimization flag and strip those out. I don't actually know though :) 

The other option is to use the white/black list options to target only certain operations that would minimize mutations in the assertions, but I realize that may not be feasible depending on the size of your source code.

**Comment by martinruefenacht** [comment]
I will test out your PUTHONOPTIMIZE suggestion over the weekend. My guess is that yes it should work.

**Comment by martinruefenacht** [comment]
I have been thinking about this for a bit. My primary concern is with assert statements, but if __name__ == "__main__" also gets mutated, which I don't think is correct either.

I have forked the repo and will work on a solution. My idea is to walk the AST and create parent links, and a mutation is attempted with a parent instance of "Assert" then the mutation is abandoned (not quite sure how to do this yet). This may only apply to Compare.

**Comment by EvanKepner** [comment]
Thanks for reaching out - you may also be able to accomplish this using the [mutatest api](https://mutatest.readthedocs.io/en/latest/api_tutorial/api_tutorial.html):

1. Scan you target file and get the list of targets for mutations.
2. Write your own separate `ast.NodeVisitor` subclass to identify `assert` statements and collect the line numbers. 
3. Filter the corresponding matching line numbers/files from the original target list.
4. Run your mutation trials.

The level of potential complexity in tracking parent nodes and accounting for edge cases like this may not be worth the maintenance burden when it can be done through use of the API instead.

**Comment by EvanKepner** [comment]
See PR #29 for discussion and a workaround method using the mutatest API.
